/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as PlayItemIdRouteImport } from './routes/play/$itemId'
import { Route as AppItemsItemIdRouteImport } from './routes/_app/items/$itemId'
import { Route as AppLibraryLibraryIdRouteImport } from './routes/_app/library/$libraryId'
import { Route as AppRequestTypeTmdbIdRouteImport } from './routes/_app/request/$type.$tmdbId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const PlayItemIdRoute = PlayItemIdRouteImport.update({
  id: '/play/$itemId',
  path: '/play/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppItemsItemIdRoute = AppItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryLibraryIdRoute = AppLibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestTypeTmdbIdRoute = AppRequestTypeTmdbIdRouteImport.update({
  id: '/request/$type/$tmdbId',
  path: '/request/$type/$tmdbId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/requests': typeof AppRequestsRoute
  '/play/$itemId': typeof PlayItemIdRoute
  '/items/$itemId': typeof AppItemsItemIdRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
  '/request/$type/$tmdbId': typeof AppRequestTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/requests': typeof AppRequestsRoute
  '/play/$itemId': typeof PlayItemIdRoute
  '/': typeof AppIndexRoute
  '/items/$itemId': typeof AppItemsItemIdRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
  '/request/$type/$tmdbId': typeof AppRequestTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/requests': typeof AppRequestsRoute
  '/play/$itemId': typeof PlayItemIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/items/$itemId': typeof AppItemsItemIdRoute
  '/_app/library/$libraryId': typeof AppLibraryLibraryIdRoute
  '/_app/request/$type/$tmdbId': typeof AppRequestTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/requests'
    | '/play/$itemId'
    | '/items/$itemId'
    | '/library/$libraryId'
    | '/request/$type/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/requests'
    | '/play/$itemId'
    | '/'
    | '/items/$itemId'
    | '/library/$libraryId'
    | '/request/$type/$tmdbId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/requests'
    | '/play/$itemId'
    | '/_app/'
    | '/_app/items/$itemId'
    | '/_app/library/$libraryId'
    | '/_app/request/$type/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayItemIdRoute: typeof PlayItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/play/$itemId': {
      id: '/play/$itemId'
      path: '/play/$itemId'
      fullPath: '/play/$itemId'
      preLoaderRoute: typeof PlayItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/items/$itemId': {
      id: '/_app/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AppItemsItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$libraryId': {
      id: '/_app/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof AppLibraryLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/request/$type/$tmdbId': {
      id: '/_app/request/$type/$tmdbId'
      path: '/request/$type/$tmdbId'
      fullPath: '/request/$type/$tmdbId'
      preLoaderRoute: typeof AppRequestTypeTmdbIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRequestsRoute: typeof AppRequestsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppItemsItemIdRoute: typeof AppItemsItemIdRoute
  AppLibraryLibraryIdRoute: typeof AppLibraryLibraryIdRoute
  AppRequestTypeTmdbIdRoute: typeof AppRequestTypeTmdbIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRequestsRoute: AppRequestsRoute,
  AppIndexRoute: AppIndexRoute,
  AppItemsItemIdRoute: AppItemsItemIdRoute,
  AppLibraryLibraryIdRoute: AppLibraryLibraryIdRoute,
  AppRequestTypeTmdbIdRoute: AppRequestTypeTmdbIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayItemIdRoute: PlayItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
